spring:
  profiles:
    active: db
  application:
    name: social-anti-fake-news-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

supabase:
  storage:
    endpoint: https://xqmkcsuwdobcdozqormi.storage.supabase.co/storage/v1/s3
    endpoint_output: https://xqmkcsuwdobcdozqormi.storage.supabase.co/storage/v1/object/public
    region: ap-northeast-2
    accessKey: 8177ceef6d9990ddb064745404258b2a
    secretKey: a4b3911f4364e3a4d03ac48df7206045b7fb9ec4d94f75cecaafc1a7e6112169
    bucket: child

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 604800000 # 7 days
